Feature/hospital map
PSW-2021-ORG7/Managers-app pull request #2
Opened 2021-11-04 15:29 UTC by racicmelanija

I fetched building data from our Hospital API and displayed it in the hospital-map component using D3.js library. I also added a route which navigates to the floor plan of the building being selected.

2021-11-04 16:44 UTC, vujsa7 requested changes
Add polygon as d3 object above the main building and change coordinations and add text on the main building.

2021-11-04 16:44 UTC, vujsa7 commented on Frontend/src/assets/surroundingObjects.json
> +    { "x": 280.87, "y": 378, "width": 138.89, "height": 57, "fill": "#bcbcbc", "stroke": "#d2d2d2" },
Fix object coordinations for front entrance of the building.

2021-11-04 16:44 UTC, vujsa7 commented on Frontend/src/app/hospital-map/buildings/buildings.component.ts
> +  mainBuilding = [
Add a polygon above the main building and let the main building be just one polygon instead of a map.

2021-11-04 19:21 UTC, anagavrilovic approved these changes

2021-11-05 00:42 UTC, vujsa7 approved these changes
Great!

2021-11-05 00:45 UTC, merged